//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int ConsultaId { get; set; }
        public string TipoConsulta { get; set; }
        public System.DateTime FechaHoraConsulta { get; set; }
        public bool Realizada { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Eliminado { get; set; }
        public int OdontologoId { get; set; }
        public int PacienteId { get; set; }
    
        public virtual Odontologo Odontologo { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
